---
title: "Cleaned Research Code"
author: "Atticus Roop"
date: "2026-04-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

All Packages

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(data.table)
library(cmdstanr)
library(rethinking)
library(yahoofinancer)
library(kernlab)
library(BART)
library(dbarts)
library(stats)
library(zoo)
```


Data
```{r}
PG <- Ticker$new("PG")

PG_data <- PG$get_history(
  start = "1980-03-03",
  interval = "1d"
)
df <- PG_data
```

Cleaning
```{r}
df <- df[, c("date", "close", "volume", "high", "low", "open", "adj_close")]
cols <- c("close","volume","high","low","open","adj_close")
df <- na.omit(df)
df[cols] <- lapply(df[cols], function(x) {
  if (is.list(x)) x <- unlist(x)
  as.numeric(x)
})
df$date <- as.POSIXct(df$date)

df <- df[complete.cases(df), ]
df <- df[order(df$date), ]
df <- na.omit(df)
```

Feature Engineering(In Progress...)
```{r}
df$return <- c(NA, diff(log(df$close)))

df$lag_ret1 <- dplyr::lag(df$return, 1)
df$lag_ret2 <- dplyr::lag(df$return, 2)

df$vol5 <- rollapply(df$return, 5, sd, fill=NA, align="right")

df$ma5 <- stats::filter(df$close, rep(1/5,5), sides=1)
df$ma10 <- stats::filter(df$close, rep(1/10,10), sides=1)

df$range <- df$high - df$low

df$lag1 <- c(NA, head(df$close, -1))
df$lag2 <- c(NA, NA, head(df$close, -2))
df$lag3 <- c(NA, NA, NA, head(df$close, -3))
df$lag4 <- c(NA, NA, NA, NA, head(df$close, -4))
df$lag5 <- c(NA, NA, NA, NA, NA, head(df$close, -5))
```


Model 1: Predicting 1 day
```{r}
df$y <- c(df$close[-1], NA)
df$date <- as.Date(df$date)
df <- df[, c("date", "y",
             "lag_ret1", "lag_ret2", "vol5", "ma10", "ma5", "range",
             "lag1", "lag2", "lag3", "lag4", "lag5",
             "volume", "open", "high", "low")]

df[] <- lapply(df, function(x) {
  if (is.list(x)) x <- unlist(x)
  x
})

num_cols <- setdiff(names(df), "date")
df[num_cols] <- lapply(df[num_cols], as.numeric)

df <- na.omit(df)
split_date <- as.Date("2026-03-03")

train <- df[df$date < split_date, ]
test  <- df[df$date >= split_date & df$date <= as.Date("2026-04-07"), ]


X_train <- as.matrix(train[, c('lag_ret1','lag_ret2','vol5','ma10','ma5','range',
                               "lag1","lag2","lag3","lag4","lag5",
                               "volume","open","high","low")])
y_train <- as.numeric(train$y)

X_test  <- as.matrix(test[, c('lag_ret1','lag_ret2','vol5','ma10','ma5','range',
                              "lag1","lag2","lag3","lag4","lag5",
                              "volume","open","high","low")])
y_test  <- as.numeric(test$y)

storage.mode(X_train) <- "double"
storage.mode(X_test)  <- "double"
set.seed(999)

fit <- dbarts::bart(
  x.train = X_train,
  y.train = y_train,
  x.test = X_test,
  ntree = 200,
  ndpost = 400,
  nskip = 200,
  keeptrees = TRUE,
  verbose = FALSE
)

yhat_train <- colMeans(fit$yhat.train)
yhat_test  <- colMeans(fit$yhat.test)


train_rmse <- sqrt(mean((y_train - yhat_train)^2))
test_rmse  <- sqrt(mean((y_test - yhat_test)^2))

train_rmse
test_rmse

```

Model 2: Predicting 5 days


Model 3: Predicting 10 days
Have to run first part again
```{r}
PG <- Ticker$new("PG")

PG_data <- PG$get_history(
  start = "1980-03-03",
  interval = "1d"
)
df <- PG_data
df <- df[, c("date", "close", "volume", "high", "low", "open", "adj_close")]
cols <- c("close","volume","high","low","open","adj_close")
df <- na.omit(df)
df[cols] <- lapply(df[cols], function(x) {
  if (is.list(x)) x <- unlist(x)
  as.numeric(x)
})
df$date <- as.POSIXct(df$date)

df <- df[complete.cases(df), ]
df <- df[order(df$date), ]
df <- na.omit(df)
df$return <- c(NA, diff(log(df$close)))

df$lag_ret1 <- dplyr::lag(df$return, 1)
df$lag_ret2 <- dplyr::lag(df$return, 2)

df$vol5 <- rollapply(df$return, 5, sd, fill=NA, align="right")

df$ma5 <- stats::filter(df$close, rep(1/5,5), sides=1)
df$ma10 <- stats::filter(df$close, rep(1/10,10), sides=1)

df$range <- df$high - df$low

df$lag1 <- c(NA, head(df$close, -1))
df$lag2 <- c(NA, NA, head(df$close, -2))
df$lag3 <- c(NA, NA, NA, head(df$close, -3))
df$lag4 <- c(NA, NA, NA, NA, head(df$close, -4))
df$lag5 <- c(NA, NA, NA, NA, NA, head(df$close, -5))
```

```{r}
df$ret10 <- c(
  log(df$close[11:nrow(df)] / df$close[1:(nrow(df) - 10)]),
  rep(NA, 10)
)

df$y <- df$ret10
df$date <- as.Date(df$date)

# Keep only rows with complete values in variables used by the model
df <- df[, c("date", "y",
             "lag_ret1", "lag_ret2", "vol5", "ma10", "ma5", "range",
             "lag1", "lag2", "lag3", "lag4", "lag5",
             "volume", "open", "high", "low")]

df[] <- lapply(df, function(x) {
  if (is.list(x)) x <- unlist(x)
  x
})

num_cols <- setdiff(names(df), "date")
df[num_cols] <- lapply(df[num_cols], as.numeric)

df <- na.omit(df)

####SPlit Data
split_date <- as.Date("2026-03-03")

train <- df[df$date < split_date, ]
test  <- df[df$date >= split_date & df$date <= as.Date("2026-04-07"), ]

###Variables Included

X_train <- as.matrix(train[, c('lag_ret1','lag_ret2','vol5','ma10','ma5','range',
                               "lag1","lag2","lag3","lag4","lag5",
                               "volume","open","high","low")])
y_train <- as.numeric(train$y)

X_test  <- as.matrix(test[, c('lag_ret1','lag_ret2','vol5','ma10','ma5','range',
                              "lag1","lag2","lag3","lag4","lag5",
                              "volume","open","high","low")])
y_test  <- as.numeric(test$y)

storage.mode(X_train) <- "double"
storage.mode(X_test)  <- "double"

###BART Model
set.seed(999)

fit <- dbarts::bart(
  x.train = X_train,
  y.train = y_train,
  x.test = X_test,
  ntree = 200,
  ndpost = 400,
  nskip = 200,
  keeptrees = TRUE,
  verbose = FALSE
)

####Prediction vs test
yhat_train <- colMeans(fit$yhat.train)
yhat_test  <- colMeans(fit$yhat.test)

###RMSE
train_rmse <- sqrt(mean((y_train - yhat_train)^2))
test_rmse  <- sqrt(mean((y_test - yhat_test)^2))

train_rmse
test_rmse
rmse_naive <- sqrt(mean((y_test - 0)^2))
rmse_naive
```

More Volatile Data + Future prediction

```{r}
TSLA <- Ticker$new("TSLA")

TSLA_data <- TSLA$get_history(
  start = "2010-06-29",
  interval = "1d"
)
df <- TSLA_data
df <- df[, c("date", "close", "volume", "high", "low", "open", "adj_close")]
cols <- c("close","volume","high","low","open","adj_close")
df <- na.omit(df)
df[cols] <- lapply(df[cols], function(x) {
  if (is.list(x)) x <- unlist(x)
  as.numeric(x)
})
df$date <- as.POSIXct(df$date)

df <- df[complete.cases(df), ]
df <- df[order(df$date), ]
df <- na.omit(df)
df$return <- c(NA, diff(log(df$close)))

df$lag_ret1 <- dplyr::lag(df$return, 1)
df$lag_ret2 <- dplyr::lag(df$return, 2)

df$ret3 <- log(df$close / dplyr::lag(df$close, 3))
df$ret5 <- log(df$close / dplyr::lag(df$close, 5))
df$ret10 <- log(df$close / dplyr::lag(df$close, 10))

df$vol5 <- rollapply(df$return, 5, sd, fill=NA, align="right")

df$ma5 <- stats::filter(df$close, rep(1/5,5), sides=1)
df$ma10 <- stats::filter(df$close, rep(1/10,10), sides=1)

df$volchg <- c(NA, diff(log(df$volume)))
df$vol10 <- rollapply(df$return, 10, sd, fill=NA, align="right")

df$momentum_vol <- df$ret5 * df$vol10

df$ma_ratio5  <- df$close / df$ma5
df$ma_ratio10 <- df$close / df$ma10

df$range <- df$high - df$low

df$lag1 <- c(NA, head(df$close, -1))
df$lag2 <- c(NA, NA, head(df$close, -2))
df$lag3 <- c(NA, NA, NA, head(df$close, -3))
df$lag4 <- c(NA, NA, NA, NA, head(df$close, -4))
df$lag5 <- c(NA, NA, NA, NA, NA, head(df$close, -5))
df$lag10 <- c(NA, NA, NA, NA, NA,NA, NA, NA, NA, NA, head(df$close, -10))
df$lag20 <- c(NA, NA, NA, NA, NA,NA, NA, NA, NA, NA,NA, NA, NA,
              NA, NA,NA, NA, NA, NA, NA, head(df$close, -20))

df$ret10 <- c(
  log(df$close[11:nrow(df)] / df$close[1:(nrow(df) - 10)]),
  rep(NA, 10)
)

df$y <- df$ret10
df$date <- as.Date(df$date)
df <- na.omit(df)

# Keep only rows with complete values in variables used by the model
df <- df[, c(
  "date","y","lag_ret1", "lag_ret2","ret3", 
  "ret5", "ret10","vol5", "vol10",
  "ma5", "ma10","ma_ratio5", "ma_ratio10","range",
  "volchg","momentum_vol", "lag1", "lag2", "lag3", "lag4", "lag5",
  "lag10", "lag20","volume", "open", "high", "low"
)]

df[] <- lapply(df, function(x) {
  if (is.list(x)) x <- unlist(x)
  x
})
df <- na.omit(df)
num_cols <- setdiff(names(df), "date")
df[num_cols] <- lapply(df[num_cols], as.numeric)


####SPlit Data
split_date <- as.Date("2026-03-03")

train <- df[df$date < split_date, ]
test  <- df[df$date >= split_date & df$date <= as.Date("2026-04-07"), ]

###Variables Included

X_train <- as.matrix(train[, c("lag_ret1", "lag_ret2","ret3", 
                               "ret5", "ret10","vol5", "vol10",
                               "ma5", "ma10","ma_ratio5", "ma_ratio10","range",
                               "volchg","momentum_vol", "lag1", "lag2", "lag3", "lag4", "lag5",
                               "lag10", "lag20","volume", "open", "high", "low")])
y_train <- as.numeric(train$y)

X_test  <- as.matrix(test[, c("lag_ret1", "lag_ret2","ret3", 
                              "ret5", "ret10","vol5", "vol10",
                              "ma5", "ma10","ma_ratio5", "ma_ratio10","range",
                              "volchg","momentum_vol", "lag1", "lag2", "lag3", "lag4", "lag5",
                              "lag10", "lag20","volume", "open", "high", "low")])
y_test  <- as.numeric(test$y)

storage.mode(X_train) <- "double"
storage.mode(X_test)  <- "double"

###BART Model
set.seed(999)

fit <- dbarts::bart(
  x.train = X_train,
  y.train = y_train,
  x.test = X_test,
  ntree = 300,
  ndpost = 400,
  nskip = 200,
  keeptrees = TRUE,
  verbose = FALSE
)

####Prediction vs test
yhat_train <- colMeans(fit$yhat.train)
yhat_test  <- colMeans(fit$yhat.test)

###RMSE
train_rmse <- sqrt(mean((y_train - yhat_train)^2))
test_rmse  <- sqrt(mean((y_test - yhat_test)^2))

train_rmse
test_rmse

rmse_SD <- sqrt(mean((y_test - 0)^2))
rmse_SD


pred_results <- data.frame(
  date = test$date,
  actual_10day_return = y_test*100,
  predicted_10day_return = yhat_test*100
)

head(pred_results) ###In Pct

```


10 Days in future from april 7

```{r}
TSLA <- Ticker$new("TSLA")

TSLA_data <- TSLA$get_history(
  start = "2010-06-29",
  interval = "1d"
)
df <- TSLA_data
df <- df[, c("date", "close", "volume", "high", "low", "open", "adj_close")]
cols <- c("close","volume","high","low","open","adj_close")
df <- na.omit(df)
df[cols] <- lapply(df[cols], function(x) {
  if (is.list(x)) x <- unlist(x)
  as.numeric(x)
})
df$date <- as.POSIXct(df$date)

df <- df[complete.cases(df), ]
df <- df[order(df$date), ]
df <- na.omit(df)
df$return <- c(NA, diff(log(df$close)))

df$lag_ret1 <- dplyr::lag(df$return, 1)
df$lag_ret2 <- dplyr::lag(df$return, 2)

df$ret3 <- log(df$close / dplyr::lag(df$close, 3))
df$ret5 <- log(df$close / dplyr::lag(df$close, 5))
df$ret10 <- log(df$close / dplyr::lag(df$close, 10))

df$vol5 <- rollapply(df$return, 5, sd, fill=NA, align="right")

df$ma5 <- stats::filter(df$close, rep(1/5,5), sides=1)
df$ma10 <- stats::filter(df$close, rep(1/10,10), sides=1)

df$volchg <- c(NA, diff(log(df$volume)))
df$vol10 <- rollapply(df$return, 10, sd, fill=NA, align="right")

df$momentum_vol <- df$ret5 * df$vol10

df$ma_ratio5  <- df$close / df$ma5
df$ma_ratio10 <- df$close / df$ma10

df$range <- df$high - df$low

df$lag1 <- c(NA, head(df$close, -1))
df$lag2 <- c(NA, NA, head(df$close, -2))
df$lag3 <- c(NA, NA, NA, head(df$close, -3))
df$lag4 <- c(NA, NA, NA, NA, head(df$close, -4))
df$lag5 <- c(NA, NA, NA, NA, NA, head(df$close, -5))
df$lag10 <- c(NA, NA, NA, NA, NA,NA, NA, NA, NA, NA, head(df$close, -10))
df$lag20 <- c(NA, NA, NA, NA, NA,NA, NA, NA, NA, NA,NA, NA, NA,
              NA, NA,NA, NA, NA, NA, NA, head(df$close, -20))
#Run After Feature Engineering!!!!

df$date <- as.Date(df$date)


df$y <- c(
  log(df$close[11:nrow(df)] / df$close[1:(nrow(df) - 10)]),
  rep(NA, 10)
)


df$feat_ret10 <- log(df$close / dplyr::lag(df$close, 10))

# keep needed columns
df <- df[, c(
  "date","close","y","lag_ret1", "lag_ret2","ret3", 
  "ret5", "feat_ret10","vol5", "vol10",
  "ma5", "ma10","ma_ratio5", "ma_ratio10","range",
  "volchg","momentum_vol", "lag1", "lag2", "lag3", "lag4", "lag5",
  "lag10", "lag20","volume", "open", "high", "low"
)]


num_cols <- setdiff(names(df), "date")
df[num_cols] <- lapply(df[num_cols], as.numeric)

xvars <- c("lag_ret1", "lag_ret2","ret3", 
           "ret5", "feat_ret10","vol5", "vol10",
           "ma5", "ma10","ma_ratio5", "ma_ratio10","range",
           "volchg","momentum_vol", "lag1", "lag2", "lag3", "lag4", "lag5",
           "lag10", "lag20","volume", "open", "high", "low")


train_all <- df[df$date <= as.Date("2026-04-07"), ]
train_all <- train_all[complete.cases(train_all[, c("y", xvars)]), ]


future_row <- df[df$date == as.Date("2026-04-07"), ]
future_row <- future_row[complete.cases(future_row[, xvars]), ]

X_all <- as.matrix(train_all[, xvars])
y_all <- train_all$y
X_future <- as.matrix(future_row[, xvars])

storage.mode(X_all) <- "double"
storage.mode(X_future) <- "double"

set.seed(999)

fit_future <- dbarts::bart(
  x.train = X_all,
  y.train = y_all,
  x.test = X_future,
  ntree = 300,
  ndpost = 2000,
  nskip = 1000,
  keeptrees = TRUE,
  verbose = FALSE
)

pred_log_return_10d <- mean(fit_future$yhat.test[,1])
pred_simple_return_10d <- exp(pred_log_return_10d) - 1
pred_price_10d <- future_row$close[1] * exp(pred_log_return_10d)

pred_log_return_10d
pred_simple_return_10d
pred_price_10d
```




